### ISSUE TITLE
[Non code Issue]: Type Error in Readme.md file

### ISSUE THREAD

**Issue by pythoniclaver** [pythoniclaver/Dent-Clack#18]
**Describe the bug**
At the FAQs section you made a typo at the first paragraph

**To Reproduce**
1. At Line ' FAQs Section'
2. See error or Suggestions 'Who all can contribute'
3. Possible fix 'Who can Contribute?'

**Expected behavior**
Expected 'Who all can contribute'

**Screenshots**

**Additional context**

**Comment by pythoniclaver** [comment]
I didn't assign you to this issue, please ask to be assigned before pulling requesting. I won't merge until you're assigned.

**Comment by manaslohani** [comment]
Can you assign this issue to me? The pr also fixed other typos in Readme.md

**Comment by pythoniclaver** [comment]
> Can you assign this issue to me? The pr also fixed other typos in Readme.md

Sure I will

**Comment by pythoniclaver** [comment]
You can now fix this typo.
