### ISSUE TITLE
[Bug]: NavLinks Alignment issue (Mobile)

### ISSUE THREAD

**Issue by pythoniclaver** [pythoniclaver/Dent-Clack#19]
**Describe the bug**
The Navlink is looking weird on small screen.

**To Reproduce**
1. Go to 'dentClack.vercel.app on your browser'
2. Click on 'the menu'
3. See error

**Expected behavior**
I expected the navliks to be aligned at the centre bottom of the screen and within the bottom and logo 

**Screenshots**
![Screenshot_20221017-080140](https://user-images.githubusercontent.com/98766202/196110554-06e2eef6-4a8b-4043-98c1-7665b6f9bc9d.png)

**Smartphone (please complete the following information):**
 - Device: Android 
 - Browser: Chrome

**Comment by Avaneesh-dev** [comment]
To make it look good, I will center the items and when the menu is open then the items below will slide down, meaning the menu will not cover the items, it will look better.

**Comment by pythoniclaver** [comment]
> I can center the items please assign it to me

I can only assign you to one issue at a time, so I will assign someone else. Thank you.

**Comment by pythoniclaver** [comment]
> I can center the items please assign it to me

I can only assign you to one issue at a time, so I will assign someone else. Thank you.

**Comment by pythoniclaver** [comment]
> To make it look good, I will center the items and when the menu is open then the items below will slide down, meaning the menu will not cover the items, it will look better.
> 

I will assign you to this. Thank you for wanting to participate 💙.

**Comment by pythoniclaver** [comment]
@Avaneesh-dev how is it going man??? You need any help or tips???

**Comment by ankitkumar0622** [comment]
hi, can you assign this to me

**Comment by pythoniclaver** [comment]
> hi, can you assign this to me

If @Avaneesh-dev says he can't fix it, I will assign you.

**Comment by Avaneesh-dev** [comment]
I will correct the issue by tomorrow! Actually I was thinking about using bootstrap css library but as I see you are using only css.... That's why it is taking time. I apologise. But i am learning a lot while working on it. Thank you so much for this opportunity.

**Comment by pythoniclaver** [comment]
> I will correct the issue by tomorrow! Actually I was thinking about using bootstrap css library but as I see you are using only css.... That's why it is taking time. I apologise. But i am learning a lot while working on it. Thank you so much for this opportunity.

Why do we participate in open source if not to learn? I gat your back, just don't break the code 😂😂😂

**Comment by Avaneesh-dev** [comment]
Hello, I have fixed this issue and raised a pull request. Only the style.css file was modified.

**Comment by pythoniclaver** [comment]
> Hello, I have fixed this issue and raised a pull request. Only the style.css file was modified.

@Avaneesh-dev This issue says, NavLinks Alignment issue (Mobile) but your PR says something different

Make sure your PR is linked to this issue @Avaneesh-dev

**Comment by Avaneesh-dev** [comment]
@pythoniclaver I have linked issue #19 to the pull request now.
