### ISSUE TITLE
[Bug]: Image Chopped Off

### ISSUE THREAD

**Issue by pythoniclaver** [pythoniclaver/Dent-Clack#20]
**Describe the bug**
Image looking weird in the testimonial section 

**To Reproduce**
1. Go to dentclack.vercel.app 
2. Scroll down to testimonial section
3. Swiper to the next slide

**Expected behavior**
I don't expect the image to be cut off.

**Screenshots**
![Screenshot_20221017-081451](https://user-images.githubusercontent.com/98766202/196112939-4960701b-ace1-409c-8e05-209e048fee1a.png)

**Smartphone (please complete the following information):**
 - Device: Android 
 - Browser: Chrome

**Comment by souviksaha27** [comment]
Hey @pythoniclaver . I am new to open source contributions, and I would like to contribute to this issue here. Can you guide me through the process?

**Comment by pythoniclaver** [comment]
> Hey @pythoniclaver . I am new to open source contributions, and I would like to contribute to this issue here. Can you guide me through the process?
Yes of course!!!
Please read the readme.md file and contribution.md file before proceeding.

**Comment by souviksaha27** [comment]
@pythoniclaver yes i have !

**Comment by pythoniclaver** [comment]
> @pythoniclaver yes i have !
> 

So I believe you now know the basic on how to get the project locally and run it on your own system???

**Comment by souviksaha27** [comment]
yes sir, and i am working on it now. Will push the code once i'm done.

**Comment by pythoniclaver** [comment]
> yes sir, and i am working on it now. Will push the code once i'm done.

Okay I will assign you. And hey, remember to always as me to assign you before work on any issues

**Comment by pythoniclaver** [comment]
Thank you for your contribution @souviksaha27 , don't forget to give us a star or don't we deserve it?😞
