### ISSUE TITLE
[Feature]: Design a Login Page

### ISSUE THREAD

**Issue by pythoniclaver** [pythoniclaver/Dent-Clack#21]
**Is your feature request related to a problem? Please describe.**
Nope it is not related to a problem but I feel that if there's a login at the nav then a login page should exist at least.

**Describe the solution you'd like**
I will create a Login page that has this website color scheme

**Comment by sandilya27** [comment]
please assign it to me

**Comment by Avaneesh-dev** [comment]
Hello, instead of a login page you can use a login modal. It will enhance user experience and will be easy to implement as well. Assign the issue to me so that I can get to work on it ASAP.

**Comment by Mannu292001** [comment]
Plz assign to me

**Comment by pythoniclaver** [comment]
> Hello, instead of a login page you can use a login modal. It will enhance user experience and will be easy to implement as well. Assign the issue to me so that I can get to work on it ASAP.

I really love you idea but will you keep it simple??? Can it be done without installing and packages??? We want to keep things simple 

If yes please create an issue and let's make this a new feature, I need to assign the first person to this issue.

**Comment by pythoniclaver** [comment]
> please assign it to me
> 

Okay I will assign you to this and hey, don't forget to give us a star 🌟.
