### ISSUE TITLE
[Bug]: Add Contributors images

### ISSUE THREAD

**Issue by pythoniclaver** [pythoniclaver/Dent-Clack#25]
**Describe the bug**
Add contributors profile images at the bottom of the readme.md file and contributing.md file

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to readme.md
2. Scroll down
3. See error

**Expected behaviour**
Expected all contributors profile images to be added as soon as their pull request is accepted.

**Comment by aryanlath** [comment]
Hi! Can you assign this issue to me?

**Comment by pythoniclaver** [comment]
> Hi! Can you assign this issue to me?
> 

Sure, my pleasure 😊

**Comment by pythoniclaver** [comment]
> Hi! Can you assign this issue to me?
> 

Thank you for wanting to collaborate though 💙

**Comment by Grey-A** [comment]
@aryanlath how far are we with the fix?

**Comment by pythoniclaver** [comment]
@aryanlath thank you for wanting to contribute but this issue have been resolved.

**Comment by pythoniclaver** [comment]
Issue Resolved.
