### ISSUE TITLE
[Bug]: Homepage edit

### ISSUE THREAD

**Issue by Grey-A** [pythoniclaver/Dent-Clack#29]
**Describe the bug**
The homepage has some grammar inaccuracies (i think) that i want to fix

**Screenshots**
![image](https://user-images.githubusercontent.com/92380257/196231256-478ea76b-da40-4b68-8e14-889ae7ee0ecb.png)
In the above image i think it should be replaced with "To take care of your needs and give you that beaming smile"

![image](https://user-images.githubusercontent.com/92380257/196231498-0f49101f-518e-44ce-9b06-bc28e882bfdd.png)
In the above above image i think LOGIN should be replaced with "Contact Us" and SPECIALIST should be changed to "Specialists" (plural)

**Comment by pythoniclaver** [comment]
> **Describe the bug**
> The homepage has some grammar inaccuracies (i think) that i want to fix
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/92380257/196231256-478ea76b-da40-4b68-8e14-889ae7ee0ecb.png)
> In the above image i think it should be replaced with "To take care of your needs and give you that beaming smile"
> 
> ![image](https://user-images.githubusercontent.com/92380257/196231498-0f49101f-518e-44ce-9b06-bc28e882bfdd.png)
> In the above above image i think LOGIN should be replaced with "Contact Us" and SPECIALIST should be changed to "Specialists" (plural)
> 
> 

The button won't be replaced with contact us!!!

We want to create a login page.

**Comment by pythoniclaver** [comment]
Create one issue at a time, this issue would be closed with immediate effect!
