### ISSUE TITLE
[Bug]: Dropdown Navbar isn't well aligned (Mobile )

### ISSUE THREAD

**Issue by Grey-A** [pythoniclaver/Dent-Clack#30]
**Describe the bug**
The navbar items on small screens arent well aligned, they lean to the right

**To Reproduce**
1. Go to Homepage on mobile
2. Click on dropdown icon (two parallel lines at top right)
3. See error

**Expected behavior**
The navbar items should be aligned in the middle with a color distinction from the navbar brand so as to make it prettier to the eyes

**Screenshots**
![image](https://user-images.githubusercontent.com/92380257/196233050-10a84dbf-b44f-42b9-80fb-9bed0af7324b.png)

**Smartphone (please complete the following information):**
 - Device: All mobile views in chrome 
 - Browser: Chrome

 [Click here to see the video ](https://vimeo.com/761135583/c493b8106d)

**Comment by vaibhv232** [comment]
assign it to me

**Comment by pythoniclaver** [comment]
> assign it to me

Sure I will, thanks for you interest in participating.
Do well to read the markdown files before pull request

**Comment by pythoniclaver** [comment]
This issue already exists and someone else have been assigned to fix this. Thank for wanting to contribute 💙.
