### ISSUE TITLE
[Feature]: Offcanvas navbar (Mobile)

### ISSUE THREAD

**Issue by Grey-A** [pythoniclaver/Dent-Clack#31]
**Is your feature request related to a problem? Please describe.**
Regarding the navbar on mobile i want to suggest we make it offcanvas instead of extension

**Describe the solution you'd like**
The navbar toggler should toggle an offcanvas menu that shadows the main page on mobile

**Describe alternatives you've considered**
We can also keep the original one but i suggest we make some sort of distinction between the navbar brand and the navitems

**Comment by rajuljha** [comment]
Hey @Grey-A @pythoniclaver . I would love to work on this feature. Can you assign this to me please?

**Comment by pythoniclaver** [comment]
> Hey @Grey-A @pythoniclaver . I would love to work on this feature. Can you assign this to me please?

Sure! Thank you for wanting to contribute to this repo.
