### ISSUE TITLE
[Bug]: Optimize images for SEO

### ISSUE THREAD

**Issue by tomoyanime** [pythoniclaver/Dent-Clack#32]
**Describe the bug**
The website is very slow because images are not optimized.

**To Reproduce**
1. Go to the homepage.
2. See error.

**Expected behavior**
The website should be faster.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by tomoyanime** [comment]
@pythoniclaver  I'd like to work on this issue for hacktoberfest.

**Comment by pythoniclaver** [comment]
> @pythoniclaver  I'd like to work on this issue for hacktoberfest.

Thank for your interest in participating for hacktoberfest through our repo.

I will assign you and please do well to read the markdown files. Thanks
