### ISSUE TITLE
[Bug]: Mobile nav not closing on link cliked

### ISSUE THREAD

**Issue by olakayCoder1** [pythoniclaver/Dent-Clack#36]
# Mobike nav toggling 
I notice on the mobile devices the navigation bar is not closing with I click on a link. I will like to fix this

**Comment by pythoniclaver** [comment]
Thanks for collaborating on our repository 💙

**Comment by pythoniclaver** [comment]
@olakayCoder1 having problem implementing this?

**Comment by olakayCoder1** [comment]
Be more descriptive

**Comment by pythoniclaver** [comment]
> Be more descriptive

@olakayCoder1 Sorry??? Did I create this issue??? You asked me to assign you to the issue you created and I did. What do you mean by I should be more descriptive?

If you don't know how to fix it, tell me and I will assign someone else. What nonsense!

**Comment by olakayCoder1** [comment]
Sorry for the misunderstood I don't really get what you meant before, but now I understand.

**Comment by olakayCoder1** [comment]
Can you assign it back to me

**Comment by olakayCoder1** [comment]
I await you to assign it to me

**Comment by pythoniclaver** [comment]
> I await you to assign it to me
> 

@olakayCoder1 can you fix it?

**Comment by olakayCoder1** [comment]
Yes
