### ISSUE TITLE
[Feature]: Dark and Light Theme

### ISSUE THREAD

**Issue by pythoniclaver** [pythoniclaver/Dent-Clack#38]
**Is your feature request related to a problem? Please describe.**
The user don't have options for themes.

**Describe the solution you'd like**
I feel like the user should be given the opportunity to choose the type of theme they want.

**Comment by parush-uppal** [comment]
Hi, I would like to work on the issue i think option of dark and light them  would be great for the website and i can provide dark theme functionality to the website.

**Comment by Anuran12** [comment]
@pythoniclaver  I would like to work on this

**Comment by parush-uppal** [comment]
Yes actually do to variety of classes and  and different color scheme being used  at different  places i am not not able to fully convert the whole website into dark theme

**Comment by pythoniclaver** [comment]
> Yes actually do to variety of classes and and different color scheme being used at different places i am not not able to fully convert the whole website into dark theme

@parush-uppal firstly, the purpose of open source is collaboration. We are teammate here, which means we are here to help but how can we help if we don't know that you have a problem. Always ask for help if you need it

**Comment by pythoniclaver** [comment]
Can you implement this or I should assign someone else???

**Comment by parush-uppal** [comment]
Yeah thanks for the reply should have asked going forward . Will keep in find thanks for solution for implement the solution provided by it works great

**Comment by pythoniclaver** [comment]
> Yeah thanks for the reply should have asked going forward . Will keep in find thanks for solution for implement the solution provided by it works great

@parush-uppal You're welcome man

**Comment by parush-uppal** [comment]
While implementing the dark them i put color #fff in root as custom and text color #000 as bcolor in root so that i can change them while implementing dark theme .Just having one problem with it

**Comment by parush-uppal** [comment]
The cards in in about section lost their border after applying dark theme rest everything is fine just this section have problem
![WhatsApp Image 2022-10-20 at 5 59 31 PM](https://user-images.githubusercontent.com/114945355/196948835-e423c680-045c-46e7-8a76-964f1c26ad92.jpeg)

**Comment by pythoniclaver** [comment]
> The cards in in about section lost their border after applying dark theme rest everything is fine just this section have problem ![WhatsApp Image 2022-10-20 at 5 59 31 PM](https://user-images.githubusercontent.com/114945355/196948835-e423c680-045c-46e7-8a76-964f1c26ad92.jpeg)

@parush-uppal this problem is easy to solve, so go to where I initially apply the border and box shadow to the cards, then create a root variable with those values and instead of giving it like 

```css
  .card {
     box-shadow: 0px 5px 15px rgba(0,0,0,.4);
  }
```

You should give it this instead
 ```css
  .card {
     box-shadow: --box-shadow;
  }
```

Then you change the box shadow color to the opposite when you toggle to dark mode 

```css
  .dark {
     --box-shadow: 0px 5px 15px rgba(225, 225, 225, 0.4);
  }
```

This should work!

**Comment by pythoniclaver** [comment]
@parush-uppal Don't forget to star this repository and also follow me on all platforms if you haven't. Thank you

I will be creating more open source, so stay updated to participate.

**Comment by pythoniclaver** [comment]
> Thanks for all your help. Have raised the pr for same please have a look and review

@parush-uppal Make all the modification I ask you to implement before making a new PR

**Comment by parush-uppal** [comment]
Raised another pr change the color button and bugs .Hope everything is fine now
