### ISSUE TITLE
half view of next slide in Testimonials part

### ISSUE THREAD

**Issue by akshay-Kalekar** [pythoniclaver/Dent-Clack#39]
![image](https://user-images.githubusercontent.com/50509605/196441208-3dde240b-d4b7-46d4-9292-c41268b7bcfa.png)
solve this issue

Kindly assign it to me

**Comment by pythoniclaver** [comment]
> @akshay-Kalekar on mobile it looks fine but on desktop if possibly make it expand instead of being scroll

@Grey-A It is more than possible but if it is being expanded it would spoil the UI. @akshay-Kalekar please don't make it expand just hide the other cards from displaying when not viewed.

**Comment by akshay-Kalekar** [comment]
okay,I will look into it

**Comment by pythoniclaver** [comment]
> Can you assign it to someone else ,I won't be able to work on this

@akshay-Kalekar Instead of asking for help, y'all give up 😂😂😂. What is the need of collaboration if you can't ask for help 🤦. Well I will assign someone else to this.

**Comment by lilphemy** [comment]
wanna take a look into this, can it be assigned to me?

**Comment by lilphemy** [comment]
well, can i handle this, if still open?

**Comment by pythoniclaver** [comment]
> well, can i handle this, if still open?

@lilphemy Thanks for your interest in contributing, I will surely assign you to this.

**Comment by lilphemy** [comment]
I was assessing the code file however, I noticed there wasn't any slider reaction occuring. Does this mean I am to build up the slider motion or to adjust the display view of the slider components?

**Comment by pythoniclaver** [comment]
> I was assessing the code file however, I noticed there wasn't any slider reaction occuring. Does this mean I am to build up the slider motion or to adjust the display view of the slider components?

@lilphemy Just adjust the slider view. You can do this in two ways, you either reduce the slider container width or you increase the gaps between the slides or you can even increase the slide width, one of these three methods should solve the problem.
