### ISSUE TITLE
[Feature]: A way to contact the medical institute 

### ISSUE THREAD

**Issue by Grey-A** [pythoniclaver/Dent-Clack#41]
**Is your feature request related to a problem? Please describe.**
The website says alot about what the medical institute does but i cant seem to find a way to contact them

**Describe the solution you'd like**
It will be nice if we have a page where we can be able to contact the medical institute for our needs

**Describe alternatives you've considered**
We can also just slap a phone number on the homepage

**Comment by Grey-A** [comment]
if possible assign it to me, ive gotten rusty

**Comment by pythoniclaver** [comment]
> if possible assign it to me, ive gotten rusty

@Grey-A I don't think having a page that displays our staffs detail is okay.

We have a Login page because there's a certain thing like dashboard, so if the users must contact they must first signup and login before having special access to talk to our staff.

**Comment by Grey-A** [comment]
what im thinking is why should they sign up? like its a medical website but everything will be done physically since we dont have any features for live chat with doctors or them viewing their patient details. So the website became somewhat like an advertisement site

**Comment by pythoniclaver** [comment]
> wwoa we still have work to do then, should i set up the backend?

You can start now If it is fine for you.

**Comment by Grey-A** [comment]
alright, should  create an issue for it or just go ahead?

**Comment by pythoniclaver** [comment]
> > alright, should create an issue for it or just go ahead?
> 
> Remember when the main application start it is going to be another version of this web application.

Don't open an issue on this and if you wanna talk to be, use the discussion platform to communicate with me. I will close this issue now. Thanks 🙏
