### ISSUE TITLE
[Bug]: Broken aspect ratio of the hero image

### ISSUE THREAD

**Issue by tomoyanime** [pythoniclaver/Dent-Clack#45]
**Describe the bug**
The aspect ratio of the hero image isn't kept on small viewport.

**To Reproduce**
1. Go to homepage.
2. Resize the window.
4. See error.

**Expected behavior**
Current hero image (Window Size: 770px).
![error](https://user-images.githubusercontent.com/31934952/196703580-599a772e-0d70-488b-a2ca-7162d710a371.png)

The aspect ratio should be kept like this.
![desired](https://user-images.githubusercontent.com/31934952/196703517-9dcf74ea-fcef-4444-bff3-2182db172464.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by tomoyanime** [comment]
Hi @pythoniclaver I'd like to work on this issue for hacktoberfest.

**Comment by pythoniclaver** [comment]
> Hi @pythoniclaver I'd like to work on this issue for hacktoberfest.

Thank you for your interest in collaborating and of course I will assign you to this :).
