### ISSUE TITLE
[Bug]: About Card Weird Look

### ISSUE THREAD

**Issue by pythoniclaver** [pythoniclaver/Dent-Clack#46]
**Describe the bug**
The padding in the cards is too small from the top-left.

**To Reproduce**
1. Go to ```https://dentclack.vercel.app/```
2. Scroll down to ```About``` section
3. View the cards

**Expected behavior**
It would be nicer if there's a little bit of more padding from the top-left.

**Screenshots**
![Screenshot_20221019-151644](https://user-images.githubusercontent.com/98766202/196717782-a64d6433-475b-41ac-ab13-6c8483f91437.png)

**Smartphone (please complete the following information):**
 - Device: Android 
 - Browser: Chrome

**Comment by pwnb0y** [comment]
assign me

**Comment by pwnb0y** [comment]
hey, @pythoniclaver I think it is not a bug I am not able to reproduce it. You got that just because the background color is white if you wish to change the background color of the box then it will look better than now. 
If you wish to change you can suggest me any color or I use this one 
![Screenshot (169)](https://user-images.githubusercontent.com/96813659/196796554-577ffad0-fc40-481c-9e58-07f10cd4abaf.png)

**Comment by pythoniclaver** [comment]
> hey, @pythoniclaver I think it is not a bug I am not able to reproduce it. You got that just because the background color is white if you wish to change the background color of the box then it will look better than now. If you wish to change you can suggest me any color or I use this one ![Screenshot (169)](https://user-images.githubusercontent.com/96813659/196796554-577ffad0-fc40-481c-9e58-07f10cd4abaf.png)

I love this @pwnb0y , you can change the color but make sure the color that will be used has our website color scheme.

I will assign you to this.

**Comment by pythoniclaver** [comment]
> hey, @pythoniclaver I think it is not a bug I am not able to reproduce it. You got that just because the background color is white if you wish to change the background color of the box then it will look better than now. If you wish to change you can suggest me any color or I use this one ![Screenshot (169)](https://user-images.githubusercontent.com/96813659/196796554-577ffad0-fc40-481c-9e58-07f10cd4abaf.png)

This color is too deep, use something lighter.
