### ISSUE TITLE
[Bug]: Remove Lorem Ipsum Issues

### ISSUE THREAD

**Issue by pythoniclaver** [pythoniclaver/Dent-Clack#48]
**Describe the bug**

**To Reproduce**
1. Go to ```https://dentclack.vercel.app```
2. Use ```CTR + F``` to search for ```Lorem Ipsum``` text

**Expected behavior**
Expected well written meaningful words

**Across All Devices**

**Comment by Avaneesh-dev** [comment]
Please assign this issue to me. I will write a good description of dental issues.

**Comment by pythoniclaver** [comment]
Thank you for your interest in contributing, I will assign you of course.
