### ISSUE TITLE
[Bug]: The login button turns white when hovered but the text does not turn black until you hover specifically on the text

### ISSUE THREAD

**Issue by adityabisoyi** [pythoniclaver/Dent-Clack#52]
**Describe the bug**
The login button turns white when hovered but the text does not turn black until you hover specifically on the text

![image](https://user-images.githubusercontent.com/109476995/196880773-e8883431-a95e-4933-bc23-8f6231b14230.png)
When the cursor is only on the button not on the inner text.

![image](https://user-images.githubusercontent.com/109476995/196881073-0ecb7303-7623-42cd-a51b-6ec34f5f462c.png)
When the cursor is on the inner text of the button.

**Expected behavior**
The text and button should change colour not matter where the cursor is inside the button.

**Additional context**
One more bug is that the navbar tabs are not fully left aligned there is some blank space  between the left margin and the tabs
![image](https://user-images.githubusercontent.com/109476995/196881622-c12074bd-0592-4c94-a8da-3dfd3bae34f2.png)

**Comment by adityabisoyi** [comment]
I would like to work on these issues please assign them to me.

**Comment by adityabisoyi** [comment]
I would like to work on this issue. Please assign me. 

Sorry for the closed completed tag. I did it by mistake.

**Comment by pythoniclaver** [comment]
> I would like to work on this issue. Please assign me.
> 
> Sorry for the closed completed tag. I did it by mistake.

No problem @adityabisoyi , I will assign you to this.

**Comment by pythoniclaver** [comment]
@adityabisoyi You created two bugs in one issue, please note that you're allowed to only solve one. Create another issue for the second bug hence, I won't merge your pull request.

**Comment by adityabisoyi** [comment]
Ok, I will solve the login button bug in one pull request and create a new issue for the second bug.

**Comment by pythoniclaver** [comment]
> Ok, I will solve the login button bug in one pull request and create a new issue for the second bug.

@adityabisoyi And I will merge them if they're bug free. Thank for your interest in contributing.
