### ISSUE TITLE
[Bug]: The login button text turns black when attempting to navigate via the keyboard

### ISSUE THREAD

**Issue by 06b** [pythoniclaver/Dent-Clack#58]
**Describe the bug**
 The login button text turns black when attempting to navigate via the keyboard.

**To Reproduce**
1. Press Tab until you reach the login button.
2. Once the login button has focus attempt to Tab again.
3. The text within the login button now receives focus which results in text appearing black on a black button.

**Expected behavior**
The login button should be able to receive focus and be legible.

**Screenshots**
![DentClack-Login-Focus-Bug](https://user-images.githubusercontent.com/1302542/197308760-a462dbf3-41ef-4337-90fa-97ecacd6a2dc.gif)

**Comment by pythoniclaver** [comment]
@06b next time wait for me to assign you to a task before making a PR. Thank for your interest in contributing.

**Comment by pythoniclaver** [comment]
@06b next time wait for me to assign you to a task before making a PR. Thank for your interest in contributing.
