### ISSUE TITLE
[Bug]: The navbar tabs are not right aligned.

### ISSUE THREAD

**Issue by adityabisoyi** [pythoniclaver/Dent-Clack#60]
**Describe the bug**
The navbar tabs (i.e. home, about services, specialists, testimonials) should be right aligned instead of center.

![image](https://user-images.githubusercontent.com/109476995/197322291-5933116c-dd77-4107-8fb0-7a724579d366.png)

**Expected behavior**
The navbar tabs should be right aligned like given below.

![image](https://user-images.githubusercontent.com/109476995/197322323-06c2d6d8-b70e-4934-b4b7-2ef32405dc29.png)

**Additional context**
I will also adjust the paddings and margins that are necessary.

**Comment by adityabisoyi** [comment]
I can solve this issue, please assign this to me.

**Comment by pythoniclaver** [comment]
> I can solve this issue, please assign this to me.

Sure I will, thanks for your interest in contributing.

**Comment by Jasleen-001** [comment]
Hey ,can I work on this issue?
