### ISSUE TITLE
[Bug]: Improving the margins of heading, of sections, when called by clicking menu

### ISSUE THREAD

**Issue by Agrim-Sharma174** [pythoniclaver/Dent-Clack#63]
**Describe the bug**
The headings of various sections are being cut in half, this doesn't seem nice

Like this:
1)
![image](https://user-images.githubusercontent.com/97873694/197347286-8de6b822-cd93-4d17-97a0-d30beb601c8b.png)

2)
![image](https://user-images.githubusercontent.com/97873694/197347321-d7809fa8-a3fd-4ebf-9dff-6fdaed88276f.png)

**To Reproduce**
1. Go to the navbar
2. Click on any section button
3. Scroll down to the particular sections
4. See the error

**Expected behavior**
There should be little bit gap between the headings and the navbar

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by pythoniclaver** [comment]
@Agrim-Sharma174 I'm so sorry for approving your issue but thank you for your interest in contributing. I will review your PR now.

**Comment by Agrim-Sharma174** [comment]
I've just created the PR, improving this
